### ISSUE TITLE
☂️ Migrate SMS format from other places

### ISSUE THREAD

**Issue by hober** [WICG/sms-one-time-codes#1]
- [x] Publish sms-one-time-codes [explainer](https://github.com/wicg/sms-one-time-codes) and [spec](https://wicg.github.io/sms-one-time-codes/)
  - [x] [Add sms-one-time-codes to WICG's biblio.json](https://github.com/WICG/admin/pull/100)
    - [x] Wait for this to propagate to https://github.com/tobie/specref/blob/master/refs/wicg.json
    - [x] Wait for this to propagate to https://github.com/tabatkins/bikeshed-data biblio
    - [x] Get one of Fantasai, Peter, or Tab to update https://github.com/tabatkins/bikeshed-data anchors
  - [ ] [Update WebOTP to cite sms-one-time-codes](https://github.com/WICG/WebOTP/pull/41)
  - [x] Drop the old explainer from [webkit/explainers](https://github.com/webkit/explainers/)
  - [x] Transfer or resolve related issues filed in [webkit/explainers](https://github.com/webkit/explainers/issues/)
    - [x] https://github.com/WebKit/explainers/issues/8
    - [x] https://github.com/WebKit/explainers/issues/11
    - [x] https://github.com/WebKit/explainers/issues/25
    - [x] https://github.com/WebKit/explainers/issues/28
  - [x] Transfer or resolve related issues filed in [WICG/WebOTP](https://github.com/WICG/WebOTP/issues/)
    - [x] https://github.com/WICG/WebOTP/issues/5
    - [x] https://github.com/WICG/WebOTP/issues/15

**Comment by hober** [comment]
This is just waiting on WICG/WebOTP#41 being merged.
